In [1]:
import numpy as np

In [5]:
np.zeros(shape=(23))

array([[[[0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.],
         ...,
         [0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.]],

        [[0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.],
         ...,
         [0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.]],

        [[0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.],
         ...,
         [0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.]],

        ...,

        [[0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.],
         ...,
         [0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.],
    

In [21]:
np.array([])

array([], dtype=float64)

In [16]:
0 / 0

ZeroDivisionError: division by zero

In [6]:
import numpy as np

In [8]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
from sklearn.model_selection import StratifiedKFold

ModuleNotFoundError: No module named 'sklearn'

In [10]:
a = np.array([1,2,3])
b = np.array([4,5,6])

In [11]:
np.concatenate([a, b])

array([1, 2, 3, 4, 5, 6])

In [12]:
np.hstack([a, b])

array([1, 2, 3, 4, 5, 6])

In [13]:
np.vstack([a, b])

array([[1, 2, 3],
       [4, 5, 6]])

In [15]:
a[np.array([0,2])]

array([1, 3])

In [1]:
import nltk

In [3]:
from nltk import pos_tag
from nltk import word_tokenize


In [9]:
pos_tag((word_tokenize("This room is too noisy")))

[('This', 'DT'), ('room', 'NN'), ('is', 'VBZ'), ('too', 'RB'), ('noisy', 'JJ')]

In [5]:
import nltk
from nltk.stem import WordNetLemmatizer 

lemmatizer = WordNetLemmatizer()

In [6]:
def pipe_lemmatization(text: str) -> str:
    txt = ""
    for w in word_tokenize(text):
        txt += lemmatizer.lemmatize(w) + ' '
    return txt.strip()

In [8]:
pipe_lemmatization("This room is too noisy")

'This room is too noisy'

In [10]:

# general tools
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import io
import re
import datetime as dt
import json
import requests
import scipy as sp
import numpy as np
import tempfile
import random
import time
import math
import statistics
import os
import sys
import warnings
warnings.filterwarnings('ignore')

# preprocessing & utils
import nltk
from nltk import pos_tag
from nltk import word_tokenize
from nltk import pos_tag
from nltk.stem import WordNetLemmatizer 
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize, sent_tokenize
from sklearn.model_selection import GridSearchCV, train_test_split
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report
from sklearn.feature_extraction.text import TfidfVectorizer, CountVectorizer

# ml models
from sklearn.naive_bayes import MultinomialNB
from sklearn.svm import LinearSVC
from sklearn.linear_model import SGDClassifier, LogisticRegression
from sklearn.neural_network import MLPClassifier

# others
from wordcloud import WordCloud
from matplotlib.ticker import FormatStrFormatter




stop_words = set(stopwords.words('english'))
lemmatizer = WordNetLemmatizer()

# processsing
def pipe_cleaningText(text: str) -> str:
    txt = text.lower()
    return txt

def pipe_removeStopWords(text: str) -> str:
    return " ".join([w for w in word_tokenize(text) if w not in stop_words])

def pipe_lemmatization(text: str) -> str:
    txt = ""
    for w in word_tokenize(text):
        txt += lemmatizer.lemmatize(w) + ' '
    return txt.strip()

def pipe_addPos(text: str) -> str:
    txt = ""
    for w in pos_tag(word_tokenize(text)):
        txt += '__'.join(w) + ' '
    return txt.strip()

def pipe_normalized(text: str, bin: int) -> str:
    txt = ""
    elements = word_tokenize(text)
    n = len(elements)
    for i, w in enumerate(elements):
        normVal = math.floor((i / (n - 1)) * (bin - 1)) + 1 if n != 1 else 1
        txt += w + '__' + str(normVal) + ' '
    return txt.strip()

def pipe_subjectCleaning(text: str) -> str:
    txt = ""
    for s in sent_tokenize(text):
        for w in pos_tag(word_tokenize(s)):
            if w[1] != 'NNP':
                continue
            txt += w[0] + ' '
    return txt.strip()

# feature extraction
def feature_tfidfUni(series: pd.Series, max_features=None) -> (sp.sparse.csr_matrix, TfidfVectorizer):
    tfidf_vectorizer = TfidfVectorizer(ngram_range=(1,1), max_features=max_features)
    tfidf_vectorizer.fit(series)
    return tfidf_vectorizer.transform(series), tfidf_vectorizer

def feature_bowUni(series: pd.Series, max_features=None) -> (sp.sparse.csr_matrix, CountVectorizer):
    bow_vectorizer = CountVectorizer(ngram_range=(1,1), max_features=max_features)
    bow_vectorizer.fit(series)
    return bow_vectorizer.transform(series), bow_vectorizer

def feature_tfidfUniBi(series: pd.Series, max_features=None) -> (sp.sparse.csr_matrix, TfidfVectorizer):
    tfidf_vectorizer = TfidfVectorizer(ngram_range=(1,2), max_features=max_features)
    tfidf_vectorizer.fit(series)
    return tfidf_vectorizer.transform(series), tfidf_vectorizer

def feature_bowUniBi(series: pd.Series, max_features=None) -> (sp.sparse.csr_matrix, CountVectorizer):
    bow_vectorizer = CountVectorizer(ngram_range=(1,2), max_features=max_features)
    bow_vectorizer.fit(series)
    return bow_vectorizer.transform(series), bow_vectorizer

# sampling
def balancing_upsampling(data: pd.DataFrame, target: int=None) -> pd.DataFrame:
    group_res = data.groupby(by=['overall'])['overall'].count()
    highest_n = max(group_res.values) if not target else target
    thedata = data[data.overall == group_res[group_res == highest_n].index[0]] if not target else data.drop(data.index)
    for i in group_res.index:
        if group_res.loc[i] == highest_n:
            continue
        tdata = data[data.overall == i]
        sample_ind = np.random.choice(tdata.index, highest_n - group_res.loc[i], replace=True)
        thedata = pd.concat([thedata, tdata, tdata.loc[sample_ind]])
    return thedata

def balancing_downsampling(data: pd.DataFrame, target: int=None) -> pd.DataFrame:
    group_res = data.groupby(by=['overall'])['overall'].count()
    lowest_n = min(group_res.values) if not target else target
    thedata = data[data.overall == group_res[group_res == lowest_n].index[0]] if not target else data.drop(data.index)
    for i in group_res.index:
        if group_res.loc[i] == lowest_n:
            continue
        tdata = data[data.overall == i]
        sample_ind = np.random.choice(tdata.index, lowest_n, replace=False)
        thedata = pd.concat([thedata, tdata.loc[sample_ind]])
    return thedata

# testing
def accuracyTrainTest(model, trainX: np.array, trainY: np.array, valX: np.array, valY: np.array, testX: np.array, testY: np.array) -> (float, float, float):
    mod = model.fit(trainX, trainY)
    yfit = mod.predict(trainX)
    ypredVal = mod.predict(valX)
    ypredTest = mod.predict(testX)
    
    # train result, validation result, test result
    return accuracy_score(trainY, yfit), accuracy_score(valY, ypredVal), accuracy_score(testY, ypredTest)
    
def loop_testing(model, n_test: int, xArr: sp.sparse.csr_matrix, yArr: np.array, testXArr: sp.sparse.csr_matrix, testYArr: np.array) -> dict[str: list([float, float])]:
    thedict = {}

    i = 0
    n = xArr.shape[0]
    n_sample = math.ceil(n / n_test)
    x_sam, y_sam = np.array([]), np.array([])
    while i < n_test:
        percent_sample = n_sample/xArr.shape[0]
        if percent_sample >= 1:
            xmain, ymain = xArr, yArr
        else:
            xmain, xArr, ymain, yArr = train_test_split(xArr, yArr, train_size=percent_sample, stratify=yArr, random_state=123)
        
        x_sam = sp.sparse.vstack((x_sam, xmain)) if x_sam.shape[0] != 0 else xmain
        y_sam = np.hstack((y_sam, ymain)) if y_sam.shape[0] != 0 else ymain
        xtrain, xtest, ytrain, ytest = train_test_split(x_sam, y_sam, train_size=0.9, stratify=y_sam, random_state=123)

        resTrain, resVal, resTest = accuracyTrainTest(model, xtrain, ytrain, xtest, ytest, testXArr, testYArr)
        thedict[x_sam.shape[0]] = [resTrain, resVal, resTest]

        i += 1
    return thedict

# visualization
def show_result(ypred: np.array, ytarget: np.array) -> None:
    label = ['Positive', 'Neutral', 'Negative']
    report = classification_report(ypred, ytarget, labels=label)
    conf_matrix = confusion_matrix(ypred, ytarget, labels=label)

    group_names = ['True Pos', 'False Neu', 'False Neg',
                   'False Pos', 'True Neu', 'False Neg',
                   'False Pos', 'False Neu', 'True Neg']
    group_percentages = ['{0:.2%}'.format(value) for value in conf_matrix.flatten() / np.sum(conf_matrix)]
    labels = [f'{v1}\n{v2}\n{v3}' for v1, v2, v3 in zip(group_names, group_percentages, conf_matrix.flatten())]
    labels = np.asarray(labels).reshape(3, 3)

    df_cm = pd.DataFrame(data=conf_matrix, index=label, columns=label)

    print(report)
    fix, axe = plt.subplots(figsize=(15, 8), nrows=1, ncols=1)
    sns.heatmap(df_cm, xticklabels=label, yticklabels=label, annot=labels, ax=axe, cmap = 'Blues', fmt = '')
    plt.show();

def visualized_loopTesting(result_loopTesting: dict[str: list([float, float])]) -> None:
    train_res, val_res, test_res = dict(), dict(), dict()
    for res in result_loopTesting:
        train_res[res] = result[res][0]
        val_res[res] = result[res][1]
        test_res[res] = result[res][2]

    fig, axe = plt.subplots(figsize=(15, 8), nrows=1, ncols=1)
    sns.lineplot(y=train_res.values(), x=train_res.keys() , ax=axe, label='train-result')
    sns.lineplot(y=val_res.values(), x=val_res.keys(), ax=axe, label='val-result')
    sns.lineplot(y=test_res.values(), x=test_res.keys(), ax=axe, label='test-result')
    axe.set_title("Highest Score: {}".format(max(test_res.values())))
    axe.set_xlabel("Dataset Size")
    axe.set_ylabel("Accuracy")
    axe.set_ylim([0.65, 1.0])
    axe.xaxis.set_major_formatter(FormatStrFormatter('%.0f'))
    plt.show();

# others
def correlation(x: list, y: list) -> float:
    x = np.array(x)
    y = np.array(y)
    bar_x = x.mean()
    bar_y = y.mean()
    sum_xixbar_yiybar = sum((x - bar_x) * (y - bar_y))
    sum_xixbar2 = sum((x - bar_x) ** 2)
    sum_yiybar2 = sum((y - bar_y) ** 2)

    numer = sum_xixbar_yiybar
    denom = (sum_xixbar2 * sum_yiybar2) ** (1 / 2)

    r = numer / denom if denom != 0 else 0

    return r

def gradient(x: list, y: list) -> float:
    p1 = [x[0], y[0]]
    p2 = [x[2], y[2]]

    numer = p1[1] - p2[1]
    denom = p1[0] - p2[0]

    return numer / denom
    

df = pd.read_json('../data/Amazon_GroceryandGourmetFood.json', lines=True)




NameError: name 'dfdata' is not defined

In [11]:
dfdata = df.copy()

In [12]:
dfdata.fillna("", inplace=True)

if len(dfdata['overall'].unique()) != 3:
    dfdata['overallOri'] = dfdata['overall']
dfdata['overall'] = dfdata['overallOri'].apply(lambda x: "Positive" if x > 3 else "Negative" if x < 3 else "Neutral")

In [13]:
target_n = 500 * 1000
dfdataMain, _ = train_test_split(dfdata, train_size=target_n / dfdata.shape[0], stratify=dfdata['overall'], random_state=123)

In [14]:
# for training & testing
target_n = 450 * 1000
dfdataTrain, dfdataTest = train_test_split(dfdataMain, train_size=target_n / dfdataMain.shape[0], stratify=dfdataMain['overall'], random_state=123)

In [15]:
# for validation
target_n = 45 * 1000
dfdataValid, dfdataTrainSub = train_test_split(dfdataTrain, train_size=target_n / dfdataTrain.shape[0], stratify=dfdataTrain['overall'], random_state=123)

In [16]:
# for validation training & testing
target_n = 40 * 1000
dfdataValidTrain, dfdataValidTest = train_test_split(dfdataValid, train_size=target_n / dfdataValid.shape[0], stratify=dfdataValid['overall'], random_state=123)

In [17]:
# upsampling minority group for validation training
if statistics.variance(dfdataValidTrain.groupby(by=['overall'])['overall'].count().values) >= 10 * 1000:
    dfdataValidTrain = balancing_upsampling(dfdataValidTrain)

In [18]:
def pipeline(txt: str) -> str:
    txt = pipe_cleaningText(txt)
    txt = pipe_lemmatization(txt)
    txt = pipe_normalized(txt, 5)
    return txt
    
tdf1 = dfdataValidTrain.copy()
tdf2 = dfdataValidTest.copy()
tdf1['reviewText'] = tdf1['reviewText'].apply(lambda x: pipeline(x))
tdf2['reviewText'] = tdf2['reviewText'].apply(lambda x: pipeline(x))

In [20]:
xArr, featureModel = feature_bowUniBi(tdf1['reviewText'], 150000)
yArr = tdf1['overall'].to_numpy()
testXArr, testYArr = featureModel.transform(tdf2['reviewText']), tdf2['overall'].to_numpy()

In [21]:
# option 4: mlp

mlp_model = MLPClassifier()
result = loop_testing(mlp_model, 10, xArr, yArr, testXArr, testYArr)
print("Correlation last 3: {:.4f}".format(correlation(list(result.keys())[-3:], [x[2] for x in result.values()][-3:])))
print("Gradient last 3: {:.4f}".format(gradient(range(1, 4), [x[2] for x in result.values()][-3:])))
visualized_loopTesting(result)

In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('../data/Amazon_Electronics.csv')

d:\Dropbox\Academics\Master (Msc)\MSC AI\Sem 2\Machine Learning\Assignment\Mini Project\SubjectSentimentModelling\env\lib\site-packages\IPython\core\interactiveshell.py:3398: DtypeWarning: Columns (10) have mixed types.Specify dtype option on import or set low_memory=False.
  exec(code_obj, self.user_global_ns, self.user_ns)


In [3]:
df.head()

overall  verified   reviewTime      reviewerID        asin  \
0        5      True  07 17, 2002  A1N070NS9CJQ2I  0060009810   
1        5     False   07 6, 2002  A3P0KRKOBQK1KN  0060009810   
2        5     False   07 3, 2002  A192HO2ICJ75VU  0060009810   
3        4     False  06 30, 2002  A2T278FKFL3BLT  0060009810   
4        5     False  06 28, 2002  A2ZUXVTW8RXBXW  0060009810   

                       style reviewerName  \
0  {'Format:': ' Hardcover'}   Teri Adams   
1  {'Format:': ' Hardcover'}     Willa C.   
2  {'Format:': ' Hardcover'}          Kit   
3  {'Format:': ' Hardcover'}       Andres   
4  {'Format:': ' Hardcover'}         John   

                                          reviewText  \
0  This was the first time I read Garcia-Aguilera...   
1  As with all of Ms. Garcia-Aguilera's books, I ...   
2  I've not read any of Ms Aguilera's works befor...   
3  This romance novel is right up there with the ...   
4  Carolina Garcia Aguilera has done it again.  S...   

                          summary  unixReviewTime vote image  
0                   Hit The Spot!      1026864000  NaN   NaN  
1  one hot summer is HOT HOT HOT!      1025913600  NaN   NaN  
2                  One Hot Summer      1025654400    2   NaN  
3               I love this book!      1025395200    3   NaN  
4                    One Hot Book      1025222400  NaN   NaN

In [4]:
df.shape[0]

20941539

In [7]:
df.groupby(by=['overall']).overall.count()

overall
1     2409983
2     1136973
3     1526548
4     3298596
5    12569439
Name: overall, dtype: int64

In [9]:
df.groupby(by=['overall']).overall.mean()

overall
1    1.0
2    2.0
3    3.0
4    4.0
5    5.0
Name: overall, dtype: float64

In [10]:
df.tail()

overall  verified   reviewTime      reviewerID        asin style  \
20941534        1      True  04 29, 2017  A1RH0C7YHWZQER  B01HJF704M   NaN   
20941535        5      True  04 17, 2017   A2955VBJEJZ4S  B01HJF704M   NaN   
20941536        5      True  03 31, 2017  A1FGCIRPRNZWD5  B01HJF704M   NaN   
20941537        5      True  02 16, 2017   AOEG7L8HI8DXJ  B01HJF704M   NaN   
20941538        5      True  02 11, 2017  A1BXCUK9AT7KWG  B01HJF704M   NaN   

           reviewerName                                         reviewText  \
20941534  Randy Garmire  Had it 1 day and it quit working, will be retu...   
20941535            BJN  Received item in 2 days. Product worked as adv...   
20941536         Brando  I have it plugged into a usb extension on my g...   
20941537           Mack            Fast delivery product was simple to use   
20941538         Clancy         Working as advertised, so far no problems.   

                              summary  unixReviewTime vote image  
20941534                         JUNK      1493424000  NaN   NaN  
20941535  Instructions easy and clear      1492387200  NaN   NaN  
20941536          Works well enough..      1490918400  NaN   NaN  
20941537                 Good product      1487203200  NaN   NaN  
20941538                   Five Stars      1486771200  NaN   NaN

In [11]:
df.isnull().sum()

overall                  0
verified                 0
reviewTime               0
reviewerID               0
asin                     0
style             10476370
reviewerName          2668
reviewText            9670
summary               4896
unixReviewTime           0
vote              18254610
image             20594419
dtype: int64

In [12]:
df[~df.reviewText.isnull()]['reviewText'].apply(lambda x: len(x.split(' ')))

0           139
1            42
2            51
3           105
4            45
           ... 
20941534     11
20941535     13
20941536     75
20941537      7
20941538      7
Name: reviewText, Length: 20931869, dtype: int64

In [15]:
import json

print(['"' + 'abcd' + '"'for _ in range(4)])

['"abcd"', '"abcd"', '"abcd"', '"abcd"', '"abcd"', '"abcd"', '"abcd"', '"abcd"', '"abcd"', '"abcd"', '"abcd"', '"abcd"', '"abcd"', '"abcd"', '"abcd"', '"abcd"', '"abcd"', '"abcd"', '"abcd"', '"abcd"', '"abcd"', '"abcd"', '"abcd"', '"abcd"', '"abcd"', '"abcd"', '"abcd"', '"abcd"', '"abcd"', '"abcd"', '"abcd"', '"abcd"', '"abcd"', '"abcd"', '"abcd"', '"abcd"', '"abcd"', '"abcd"', '"abcd"', '"abcd"', '"abcd"', '"abcd"', '"abcd"', '"abcd"', '"abcd"', '"abcd"', '"abcd"', '"abcd"', '"abcd"', '"abcd"', '"abcd"', '"abcd"', '"abcd"', '"abcd"', '"abcd"', '"abcd"', '"abcd"', '"abcd"', '"abcd"', '"abcd"', '"abcd"', '"abcd"', '"abcd"', '"abcd"', '"abcd"', '"abcd"', '"abcd"', '"abcd"', '"abcd"', '"abcd"', '"abcd"', '"abcd"', '"abcd"', '"abcd"', '"abcd"', '"abcd"', '"abcd"', '"abcd"', '"abcd"', '"abcd"', '"abcd"', '"abcd"', '"abcd"', '"abcd"', '"abcd"', '"abcd"', '"abcd"', '"abcd"', '"abcd"', '"abcd"', '"abcd"', '"abcd"', '"abcd"', '"abcd"', '"abcd"', '"abcd"', '"abcd"', '"abcd"', '"abcd"', '"abcd"',

In [36]:
','.join([str(1) for _ in range(1000)])

'1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1

In [39]:
''.join(['abcd' for a in range(500)])

'abcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabc

In [42]:
[-1] + [x for x in range(6)]

[-1, 0, 1, 2, 3, 4, 5]

In [43]:
import random

In [85]:
for _ in range(50):
    print('[' + ','.join([str(random.randint(-10, 10)) for _ in range(10)]) + ']')

[-2,-9,-1,-5,10,0,8,10,1,-9]
[1,3,3,10,7,-10,-7,-4,-1,-3]
[-1,8,-6,-3,4,-10,-6,-6,-2,1]
[2,-2,2,4,-4,5,6,-2,-6,2]
[4,2,6,-10,7,-9,5,-10,-5,-6]
[1,10,1,-4,-7,6,0,7,-8,-2]
[3,10,7,5,-5,-5,6,-6,1,-8]
[-3,10,-3,-2,-2,-9,1,-9,4,6]
[-7,8,-9,-7,-2,-2,-6,-10,8,-2]
[-2,-8,10,6,-1,-1,5,-4,9,-7]
[6,1,4,5,-7,9,8,-3,-1,-3]
[-5,-10,9,-9,-3,8,-4,-8,-10,2]
[7,-2,-9,-9,-6,9,-3,-3,1,-10]
[5,5,2,8,-1,-7,-6,5,-6,-4]
[-7,-10,6,-2,2,-5,-1,-2,10,2]
[-2,-1,8,-5,-7,0,5,-8,-5,10]
[-9,-9,4,-6,-6,7,4,-3,-10,-5]
[8,7,-1,9,-7,-5,-2,9,-1,7]
[6,6,9,7,-5,2,-4,-6,5,-4]
[1,-7,4,-8,-2,6,-2,-6,10,9]
[-5,-5,7,6,6,7,-3,2,-9,5]
[-1,4,-5,-8,0,-5,-5,-6,-10,-2]
[-9,-3,9,0,3,7,-4,9,-9,-9]
[-10,7,8,4,-7,-10,0,10,-4,-5]
[-3,4,5,9,-4,-2,2,5,5,6]
[-8,6,10,1,-9,6,-3,-2,9,6]
[-1,1,-8,-2,-2,-10,-7,8,-4,8]
[1,9,-1,-4,1,-2,3,-10,9,-6]
[-8,8,-7,7,-1,3,5,2,-8,6]
[8,-1,-4,8,-6,-1,0,-6,8,2]
[4,9,-8,5,-5,0,-5,9,10,-9]
[5,-1,-7,7,6,-6,-6,9,-9,-4]
[-8,2,2,9,6,5,-4,-6,-2,-10]
[-5,-8,-4,1,3,-7,6,-9,3,7]
[-7,10,-9,-3,0,5,-2,-5,3,7]
[-6,-6,-8,6,3,-

In [106]:
bin(23)

'0b10111'

In [ ]:
101 -> 

In [113]:
4 >> 2

1

In [ ]:
10 -> 100

In [111]:
2 << 1

4

In [109]:
format(4294967293, 'b')

'11111111111111111111111111111101'

In [104]:
','.join([str(random.randint(1, 500)) for _ in range(5000)])

'54,298,465,243,216,92,136,124,434,223,304,219,249,232,165,276,344,136,12,229,183,158,482,196,138,264,404,377,80,335,207,415,173,65,165,319,334,52,427,354,256,112,63,480,458,370,342,191,485,63,289,264,126,202,61,248,474,491,365,455,290,158,450,339,268,304,323,122,262,67,137,417,484,268,422,367,72,379,10,491,161,326,86,303,27,355,425,201,450,124,134,356,246,218,402,341,416,475,356,477,38,316,5,135,149,481,215,73,394,6,492,368,135,331,295,100,93,200,496,80,21,84,114,379,261,440,236,14,59,143,261,90,181,195,36,31,81,318,347,497,233,374,240,91,189,11,406,310,319,18,301,164,316,403,400,56,130,209,1,109,154,152,100,122,100,230,355,237,408,485,3,338,230,460,411,395,361,385,82,443,17,486,40,221,210,171,418,422,425,221,238,335,72,323,365,496,114,270,220,238,179,383,195,208,12,31,83,189,184,373,329,404,442,482,65,92,130,17,379,403,17,137,178,85,307,282,254,442,82,385,217,254,39,482,323,233,431,69,456,82,474,283,260,374,493,496,367,481,33,184,347,197,173,122,43,430,13,222,251,211,20,51,384,98,233

In [57]:
','.join([str([random.randint(-100, 100),random.randint(-100, 100)]) for _ in range(100)])

'[26, -71],[-35, -63],[96, 23],[82, -79],[-45, 87],[-81, 91],[18, 63],[-56, 82],[98, -84],[-7, -75],[44, -75],[-4, 8],[-27, -6],[-86, -96],[3, 37],[-22, -94],[-39, -1],[38, -15],[-15, -70],[-61, -81],[-47, 63],[45, 30],[-14, 5],[68, 43],[-65, -10],[59, -19],[68, -86],[-75, 73],[11, 28],[-58, 17],[88, -39],[-77, -23],[17, -35],[0, -93],[12, -70],[34, -94],[27, 93],[50, -66],[14, 97],[17, -1],[-47, -22],[-73, 74],[43, 100],[-71, 56],[36, 11],[67, 19],[-9, 58],[-72, -38],[47, 95],[89, 53],[6, 92],[-99, 56],[-37, 11],[-47, 100],[3, 74],[-73, -87],[-80, -92],[64, -53],[-6, 62],[9, 67],[35, 46],[36, -47],[70, -22],[-12, 24],[-19, 43],[-41, 64],[-84, 48],[11, -80],[37, 90],[-63, -51],[54, -5],[95, -90],[-25, 53],[4, 91],[100, 68],[-46, -47],[78, -55],[18, -48],[39, 9],[-68, -83],[89, -7],[62, -23],[-85, 27],[-73, 31],[-92, -55],[33, -63],[88, 47],[25, -9],[-96, 47],[-75, -59],[-32, -83],[-32, -40],[-80, 12],[76, 58],[98, -98],[-30, -46],[-85, 20],[24, -45],[36, -95],[-7, -43]'

In [59]:
'-1'.isdigit()

False

In [63]:
int(6/-123)

0

In [64]:
abs(23 / -23434)

0.0009814799009985492

In [65]:
23 / -23434

-0.0009814799009985492

In [66]:
-23 / 23434

-0.0009814799009985492

In [67]:
abs(23 / 23434)

0.0009814799009985492

In [70]:
import math

tdict = {}
tdict[math.inf] = 1
tdict[math.inf] += 1
print(tdict)

{inf: 2}


In [71]:
tdict[-0.0] = 234
tdict[0.0] = 23123

In [72]:
tdict

{inf: 2, -0.0: 23123}

In [3]:
import math

math.pow(0, 2)
math.pow(2, 0)

1.0

In [11]:
{'asdf': 2323}

{'asdf': 2323}

In [9]:
';asdf'[::-1]

'fdsa;'

In [8]:
(1 << 31) % 6 == 0

False

In [103]:
for _ in range(20):a
    t = random.randint(-10, 10)
    print(t if t != 0 else 3)

-7
-5
-10
8
-10
-4
3
-4
-7
-9
6
7
-1
-6
-4
3
-5
9
1
4


In [16]:
import random
for _ in range(10):
    print('"' + str(random.randint(1, 1000000000)) + str(random.randint(1, 1000000000)) + '"')

"913725630286854126"
"188311830977399845"
"556516765683311597"
"649308201484735507"
"972700636140441909"
"591683458947262673"
"613203396175981802"
"684830436697611268"
"757683996369211159"
"679346364356288549"


In [ ]:
[[1, 2, 3, 4, 5, 6, 7, 8, 9, 10], [2, 3, 4, 5, 6, 7, 8, 9, 10, 11], [3, 4, 5, 6, 7, 8, 9, 10, 11, 12], [4, 5, 6, 7, 8, 9, 10, 11, 12, 13], [5, 6, 7, 8, 9, 10, 11, 12, 13, 14], [6, 7, 8, 9, 10, 11, 12, 13, 14, 15], [7, 8, 9, 10, 11, 12, 13, 14, 15, 16], [8, 9, 10, 11, 12, 13, 14, 15, 16, 17], [9, 10, 11, 12, 13, 14, 15, 16, 17, 18], [10, 11, 12, 13, 14, 15, 16, 17, 18, 19], [11, 12, 13, 14, 15, 16, 17, 18, 19, 20], [12, 13, 14, 15, 16, 17, 18, 19, 20, 21], [13, 14, 15, 16, 17, 18, 19, 20, 21, 22], [14, 15, 16, 17, 18, 19, 20, 21, 22, 23], [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]]
[[1, 1, 1, 1, 1, 1, 1, 1, 1, 1], [1, 2, 3, 4, 5, 6, 7, 8, 9, 10], [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], [1, 2, 3, 4, 5, 6, 7, 8, 9, 10], [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], [1, 2, 3, 4, 5, 6, 7, 8, 9, 10], [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], [1, 2, 3, 4, 5, 6, 7, 8, 9, 10], [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], [1, 2, 3, 4, 5, 6, 7, 8, 9, 10], [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], [1, 2, 3, 4, 5, 6, 7, 8, 9, 10], [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], [1, 2, 3, 4, 5, 6, 7, 8, 9, 10], [2, 3, 4, 5, 6, 7, 8, 9, 10, 11]]


In [41]:
math.tan(90)

-1.995200412208242

In [39]:
math.tan(1/40)

0.025005209635746147

In [33]:
for r in [[0,1,2,3,4,5,6,7,8,9],[19,18,17,16,15,14,13,12,11,10],[20,21,22,23,24,25,26,27,28,29],[39,38,37,36,35,34,33,32,31,30],[40,41,42,43,44,45,46,47,48,49],[59,58,57,56,55,54,53,52,51,50],[60,61,62,63,64,65,66,67,68,69],[79,78,77,76,75,74,73,72,71,70],[80,81,82,83,84,85,86,87,88,89],[99,98,97,96,95,94,93,92,91,90],[100,101,102,103,104,105,106,107,108,109],[119,118,117,116,115,114,113,112,111,110],[120,121,122,123,124,125,126,127,128,129],[139,138,137,136,135,134,133,132,131,130],[0,0,0,0,0,0,0,0,0,0]]:
    print(r)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
[19, 18, 17, 16, 15, 14, 13, 12, 11, 10]
[20, 21, 22, 23, 24, 25, 26, 27, 28, 29]
[39, 38, 37, 36, 35, 34, 33, 32, 31, 30]
[40, 41, 42, 43, 44, 45, 46, 47, 48, 49]
[59, 58, 57, 56, 55, 54, 53, 52, 51, 50]
[60, 61, 62, 63, 64, 65, 66, 67, 68, 69]
[79, 78, 77, 76, 75, 74, 73, 72, 71, 70]
[80, 81, 82, 83, 84, 85, 86, 87, 88, 89]
[99, 98, 97, 96, 95, 94, 93, 92, 91, 90]
[100, 101, 102, 103, 104, 105, 106, 107, 108, 109]
[119, 118, 117, 116, 115, 114, 113, 112, 111, 110]
[120, 121, 122, 123, 124, 125, 126, 127, 128, 129]
[139, 138, 137, 136, 135, 134, 133, 132, 131, 130]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]


In [29]:
import random
for _ in range(100):
    print('"' + ''.join([chr(random.randint(ord('a'), ord('z'))) for _ in range(100)]) + '"')

"yebhqpxllztllvvmojipavqjodbuoxnltojrlsnzglfsmygdaixqbhkigobmodoezidfbphxkabkvtiaoxteovsmaaqwuygywpvu"
"jerbbxmkxddckangvgyychdbvkwkkzcybjwemauucnbdajigqeqnsamttvwzjntwpenrpmsfiqmqhlftnudigrorfbzatigrpvyo"
"pwbbmqcmiwwbabcgwbwrttwbqrwbybizzkzkgvnvipedhjgbgozfequfcdnvohmsghnzgajunlbpzmwuwwqhniworoipzotjatxg"
"jydiatcbzyshwiiuoxkvbhfmnougumprorlvsthumgiimfzxjuwlpkskegvtbmabpdldeoqceqeimqxyhtuqfvtntklqymfvkgmb"
"bzfgfxwochkyckbuvkaamyfdkrovxvpqitacbxchwgrmptpmusobltluihlxhhixrllgbmjnfwpvhetzfpgxejrthmejhnxeundh"
"odqyrulumqbbglzfhoeeqwkstfnbazhorihcmsxkneqziefddfeyzpgywqxwoyiijcejfqthcoagpeotzfnzkqcczubrllomjbqa"
"dkhaetbpwbpddlluusfxkxbpsoaqmwdiwfpkqtfyupudxamdtzjgzdhzrfplazdksvcgmlupmzuhmbnfikgyawkkxekdrdxixzus"
"cumhzeqohkhmecfvioxyjiscytagtzxlgtowsritybicfmideoavtuwzqkdtjhttnomzzfqgfzwcichowgucrmtkeosvytmekxze"
"pdnlyaddgtphbuncsxjxprcxzgpaxmlkklmjeaqceauaiyyvnnxzsypqyyxowsreohosbeewtsnihgtpowqioyxsuomkxvbsuwwf"
"zawhvudwgzrqmyljmnfxpcmwjtwoyzlhmpivnyoftkozghwjahfjamldnojfjtkouknrjkoy

In [23]:
import random
for _ in range(100):
    print('[' + ','.join([str(random.randint(1, 4)) for _ in range(10)]) + ']')

[3,4,2,4,4,3,1,1,3,1]
[4,3,3,2,3,3,3,2,4,4]
[3,1,2,3,1,2,2,4,2,2]
[2,3,1,1,3,1,1,4,1,2]
[2,4,4,1,2,3,2,4,1,4]
[4,4,4,3,1,1,1,1,3,3]
[3,4,3,1,1,3,1,2,4,3]
[2,4,1,3,3,4,2,2,2,2]
[1,3,3,2,1,4,2,4,3,4]
[2,1,4,2,2,3,4,4,2,3]
[3,3,1,3,1,1,4,4,1,3]
[3,3,3,1,4,2,4,4,1,4]
[3,2,3,2,4,2,4,1,4,3]
[1,1,2,1,2,3,1,3,4,1]
[4,1,3,1,4,2,2,2,4,3]
[1,3,2,1,2,1,2,4,3,3]
[3,2,4,2,1,2,1,3,2,1]
[1,4,3,3,3,1,4,3,4,1]
[3,1,2,4,1,1,1,1,4,3]
[3,2,2,3,4,2,1,4,4,2]
[3,4,2,3,1,2,4,2,1,3]
[2,3,3,3,3,4,1,3,2,4]
[4,4,4,2,4,1,2,4,4,2]
[3,1,1,4,2,2,4,1,1,2]
[3,4,4,4,4,2,2,2,1,3]
[1,2,3,2,2,4,2,3,4,4]
[1,3,3,4,3,2,2,2,1,2]
[2,2,2,4,3,2,2,4,4,1]
[1,1,3,1,2,2,2,3,1,1]
[2,2,1,3,1,4,1,1,3,4]
[1,4,2,2,2,3,3,2,2,3]
[4,2,3,3,3,3,3,3,4,3]
[3,4,3,4,1,1,1,4,2,2]
[4,4,4,1,3,3,2,2,3,1]
[2,1,4,4,1,2,2,2,2,4]
[3,1,3,4,2,2,2,3,4,2]
[3,2,2,2,1,1,4,2,3,3]
[3,1,2,2,4,4,2,1,1,3]
[1,2,1,3,3,4,2,2,2,2]
[2,4,3,2,4,4,2,1,2,2]
[1,3,2,3,1,1,4,1,1,3]
[4,2,3,4,3,2,4,1,2,2]
[3,1,1,4,1,1,2,3,2,3]
[3,3,3,3,4,4,2,1,1,4]
[4,1,4,4,2,1,2,2,2,4]
[3,2,3,4,3

In [19]:
3**-23

1.062211848441645e-11

In [1]:
for _ in range(100):
    print(random.randint(2, 9))
    print(random.randint(1, 60))

NameError: name 'random' is not defined