In [1]:
import numpy as np

In [5]:
np.zeros(shape=(23))

array([[[[0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.],
         ...,
         [0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.]],

        [[0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.],
         ...,
         [0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.]],

        [[0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.],
         ...,
         [0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.]],

        ...,

        [[0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.],
         ...,
         [0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.],
    

In [16]:
0 / 0

ZeroDivisionError: division by zero

In [6]:
import numpy as np

In [8]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
from sklearn.model_selection import StratifiedKFold

ModuleNotFoundError: No module named 'sklearn'

In [10]:
a = np.array([1,2,3])
b = np.array([4,5,6])

In [11]:
np.concatenate([a, b])

array([1, 2, 3, 4, 5, 6])

In [12]:
np.hstack([a, b])

array([1, 2, 3, 4, 5, 6])

In [13]:
np.vstack([a, b])

array([[1, 2, 3],
       [4, 5, 6]])

In [15]:
a[np.array([0,2])]

array([1, 3])